{"name": "test_x[5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 2\n +  where 2 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\n +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint", "trace": "x = 5\n\n    @pytest.mark.parametrize('x', data)\n    def test_x(x):\n>       assert x == random.randint(1,3)\nE       assert 5 == 2\nE        +  where 2 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\nE        +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint\n\ntest_pytest2.py:22: AssertionError"}, "parameters": [{"name": "x", "value": "5"}], "start": 1597154468297, "stop": 1597154468298, "uuid": "ef177845-382b-4135-91cf-2e5f4263429b", "historyId": "d286c2b5225d8282907857833e86b064", "testCaseId": "b1db76a50f52df3788772fa82f169c41", "fullName": "test_pytest2#test_x", "labels": [{"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest2"}]}